project: art
default_services: 
  - dev
  - vnc
custom_cli_arguments:
  --gpus:
    argparse:
      action: 'store_true'
    dev:
      runtime: nvidia
    chrono:
      runtime: nvidia
  --vnc-password:
    argparse:
      default: ""
    vnc:
      build:
        args:
          VNC_PASSWORD: "{vnc_password}"
services:
  dev:
    build:
      args:
        APT_DEPENDENCIES: "bash zsh vim git git-lfs python3-pip python3-tk python3-opencv"
        PIP_REQUIREMENTS: "torch matplotlib numpy>=1.20 opencv-python"
  vnc:
    build:
      args:
        VNC_PASSWORD: "{vnc_password}"
  chrono:
    image: "atk/{project}:chrono"
    hostname: "{project}-chrono"
    container_name: "{project}-chrono"
    build:
      context: ./docker/chrono
      dockerfile: ./chrono.dockerfile
      network: "host"
      args:
        USERNAME: "{project}"
        APT_DEPENDENCIES: "libirrlicht-dev"
        CONDA_CHANNELS: "anaconda conda-forge"
        CONDA_DEPENDENCIES: "python=3.8.12 pip pychrono cudatoolkit anaconda-client conda-build"
        PIP_DEPENDENCIES: ""
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "all"
    ports:
      - "50000:50000"
    working_dir: "/home/{username}/{project}/sim"
    volumes: 
      - "{root}:/home/{username}/{project}"
    tty: true
